name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Run Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Run Tests with Coverage
        run: |
          mkdir -p coverage
          go test -coverprofile=coverage/coverage.out ./...

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.out

  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true

      - name: Set Version Output
        run: echo "VERSION=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_ENV
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6

      - name: Set Git Branch
        id: set_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "GIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "GIT_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@dd734f74fce61a6e02f821ee1b5930bc79a23534 # v5
        id: changelog
        with:
          github-token: ${{ github.token }}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          version-file: .github/package.yaml
          create-summary: true
          skip-git-pull: true
          preset: "conventionalcommits"
          git-branch: '${{ env.GIT_BRANCH }}'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test, calculate-version, gitleaks]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build CLI Binary
        run: |
          mkdir -p dist
          go build -o dist/mentionR

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cli-binary
          path: dist/mentionR

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, calculate-version]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: cli-binary
          path: dist

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{needs.calculate-version.outputs.fullSemVer}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: "${{needs.calculate-version.outputs.fullSemVer}}"
          name: "Release ${{needs.calculate-version.outputs.fullSemVer}}"
          files: |
            dist/mentionR